before_install:
  - sudo apt-get update -qq
  - sed 's/#deb http://archive.canonical.com/ubuntu precise partner/deb http://archive.canonical.com/ubuntu precise partner/g' /etc/apt/sources.list
  - sudo apt-get install -y db2 db2-dev
