before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y db2 db2-dev
  - sed 's/#deb http://archive.canonical.com/ubuntu lucid partner/deb http://archive.canonical.com/ubuntu lucid partner/g' /etc/apt/sources.list
  - cat deb http://archive.canonical.com/ubuntu lucid partner
